/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpborestoran;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;


/**
 *
 * @author ASUS Vivobook
 */
public class Order extends javax.swing.JFrame {
    DefaultTableModel modelMenu;


    /**
     * Creates new form BisaPesan
     */
    public Order() {
        initComponents();
        
        modelMenu = new DefaultTableModel(
        new Object[][] {},
        new String[] { "ID", "Nama Menu", "Harga", "Kategori", "Jumlah" }
          ) {
    // Hanya kolom Jumlah (ke-4, index 4) yang bisa diedit
        @Override
        public boolean isCellEditable(int row, int col) {
        return col == 4;
        }
        @Override
        public Class<?> getColumnClass(int column) {
        if (column == 4) return Integer.class; // Jumlah
        if (column == 0) return Integer.class; // ID
        if (column == 2) return Integer.class; // Harga
        return String.class;
        }
        };
        tblMenu.setModel(modelMenu);
        modelMenu.addTableModelListener(e -> hitungTotal());
        loadCustomers();
        loadMenuItems();
        hitungTotal();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Pesan Menu Restoran ASIK");

        btnSimpan.setText("simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");

        jLabel2.setText("Customer :");

        jLabel3.setText("Daftar Menu");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTotal.setText("Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnSimpan)
                        .addGap(36, 36, 36)
                        .addComponent(btnReset)
                        .addGap(26, 26, 26)
                        .addComponent(btnKembali)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnKembali)
                    .addComponent(btnReset))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        simpanPesanan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    
    private void hitungTotal() {
    int total = 0;
    DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        int harga = Integer.parseInt(model.getValueAt(i, 2).toString());     // Kolom Harga
        int jumlah = 0;
        // Cegah error jika kolom belum diisi
        Object val = model.getValueAt(i, 4);
        if (val != null && !val.toString().isEmpty()) {
            try {
                jumlah = Integer.parseInt(val.toString());
            } catch (NumberFormatException ex) {
                jumlah = 0;
            }
        }
        total += harga * jumlah;
    }
    lblTotal.setText("Rp " + total);
}
    
    private void loadCustomers() {
    try {
        Connection conn = koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT customer_id, name FROM customers");
        cmbCustomer.removeAllItems();
        while (rs.next()) {
            cmbCustomer.addItem(rs.getInt("customer_id") + " - " + rs.getString("name"));
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load customer: " + e.getMessage());
    }
}
    
    private void resetForm() {
    cmbCustomer.setSelectedIndex(0);
    for (int i = 0; i < modelMenu.getRowCount(); i++) {
        modelMenu.setValueAt(0, i, 4); // kolom jumlah jadi 0
    }
    hitungTotal();
}

    private void simpanPesanan() {
    if (cmbCustomer.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih customer dulu!");
        return;
    }

    int total = 0;
    for (int i = 0; i < modelMenu.getRowCount(); i++) {
        int harga = Integer.parseInt(modelMenu.getValueAt(i, 2).toString());
        int jumlah = 0;
        Object val = modelMenu.getValueAt(i, 4);
        if (val != null && !val.toString().isEmpty()) {
            try { jumlah = Integer.parseInt(val.toString()); } catch (Exception ex) { jumlah = 0; }
        }
        total += harga * jumlah;
    }

    if (total == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Isi jumlah pesanan!");
        return;
    }

    // Ambil customer id
    String selected = cmbCustomer.getSelectedItem().toString();
    int customerId = Integer.parseInt(selected.split(" - ")[0]);
    
    try {
        Connection conn = koneksi.getConnection();
        // 1. Insert orders
        String sqlOrder = "INSERT INTO orders (customer_id, order_date, total) VALUES (?, NOW(), ?)";
        PreparedStatement pstOrder = conn.prepareStatement(sqlOrder, java.sql.Statement.RETURN_GENERATED_KEYS);
        pstOrder.setInt(1, customerId);
        pstOrder.setInt(2, total);
        pstOrder.executeUpdate();
        ResultSet rs = pstOrder.getGeneratedKeys();
        int orderId = 0;
        if (rs.next()) orderId = rs.getInt(1);
        pstOrder.close();

        // 2. Insert orderdetails
        String sqlDetail = "INSERT INTO orderdetails (order_id, item_id, quantity) VALUES (?, ?, ?)";
        PreparedStatement pstDetail = conn.prepareStatement(sqlDetail);
        for (int i = 0; i < modelMenu.getRowCount(); i++) {
            int jumlah = Integer.parseInt(modelMenu.getValueAt(i, 4).toString());
            if (jumlah > 0) {
                int menuId = Integer.parseInt(modelMenu.getValueAt(i, 0).toString());
                pstDetail.setInt(1, orderId);
                pstDetail.setInt(2, menuId);
                pstDetail.setInt(3, jumlah);
                pstDetail.addBatch();
            }
        }
        pstDetail.executeBatch();
        pstDetail.close();

        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil disimpan!");
        resetForm();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal simpan pesanan: " + e.getMessage());
    }
}
    
    private void loadMenuItems() {
    modelMenu.setRowCount(0); // Bersihkan tabel
    try {
        Connection conn = koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT item_id, name, price, category FROM menuitems");
        while (rs.next()) {
            modelMenu.addRow(new Object[]{
                rs.getInt("item_id"),
                rs.getString("name"),
                rs.getInt("price"),
                rs.getString("category"),
                0 // jumlah default
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load menu: " + e.getMessage());
    }
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
